printWidth: 80
tabWidth: 4
useTabs: false
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
trailingComma: all
bracketSpacing: true
bracketSameLine: false
arrowParens: always
htmlWhitespaceSensitivity: ignore
vueIndentScriptAndStyle: false
endOfLine: lf
